#ifndef BADWORDS_H
#define BADWORDS_H

#include <QSet>
#include <QString>

/**
 * @file badwords.h
 * @brief Bad words lists for adult content detection (ported from legacy bad-words.js)
 * 
 * XXX_BLOCK_WORDS - words that mark torrent as XXX category
 * XXX_VERY_BAD_WORDS - words that mark torrent as BAD type (blocked entirely)
 */

namespace BadWords {

// Words that mark content as XXX category
inline const QSet<QString>& xxxBlockWords()
{
    static QSet<QString> words = {
        "incestcash", "asacp", "xondemand", "yankscash", "klixxx", "cybersitter", "safesurf", 
        "surfwatch", "netcash", "watersport", "fuck", "threesome", "tits", 
        "masturbating", "incest", "bestiality", "analintercourse", "analsex", "animesex", 
        "anitablonde", "autosex", "blackass", "blackasses", "boner", "boobcruise", 
        "boobies", "bordello", "braless", "brothel", "callgirl", "callgirls", 
        "clit", "clitoris", "clits", "cums", "cybererotic", "cybererotica", 
        "cybersex", "cybersexx", "ejaculation", "erotica", "eroticfilm", "eroticfilms", 
        "eroticism", "eroticphoto", "eroticphotography", "eroticphotos", "erotics", "eroticsex", 
        "eroticsexstories", "eroticstories", "eroticstory", "erotik", "erotika", "antasysex", 
        "gaysex", "gruppensex", "horny", "jackoff", "lesbo", "lesbos", 
        "makinglove", "motherfucker", "horsesex", "dogsex", "snakesex", "sextracker", 
        "tranny", "bdsm", "porn", "beastality", "bizarre", "blowjob", 
        "bondage", "bondages", "celebs", "cum", "cunt", "transsexual", 
        "transsexuals", "cumbath", "cumshot", "dildo", "dildos", "transvestites", 
        "transvestite", "dominatrix", "spank", "dungeon", "sexbilder", "dungeons", 
        "pussie", "ebony", "fisting", "gayshop", "facesitting", "sexshop", 
        "pussy", "bukkake", "escort", "blowjobs", "facial", "facialized", 
        "facials", "fetish", "footfetish", "fuckingpussy", "fucking", "hardcore", 
        "hentai", "hustlerlatex", "latex", "lolita", "lolitas", "mlm", 
        "oralsex", "peepshow", "peepshows", "phonesex", "pornstars", "preteen", 
        "preteens", "pussies", "shemale", "shemales", "sluts", "whores", 
        "whore", "spanking", "strapon", "twinks", "upskirts", "voyeur", 
        "whip", "whipping", "xxx", "sexkey", "femdom", "gangbang", 
        "gloryhole", "adultbuffet", "adultcartoons", "adultchat", "adultchatnetwork", "adultdvd", 
        "adultentertainment", "adultentertainmenthouse", "adulterotica", "adultfilms", "adultfree", "adultfreepics", 
        "adultfreepix", "adultfun", "adulthardcore", "adultimages", "adultjpeg", "adultlink", 
        "adultlinks", "adultmovie", "adultmovies", "adultmpeg", "adultmpegs", "adultpass", 
        "adultpersonals", "adultphotos", "adultpic", "adultpics", "adultpicture", "adultpictures", 
        "adultpix", "adultporn", "adultpornography", "adultsearch", "adultsex", "adultsights", 
        "adultsites", "adultsonly", "adultstars", "adultstories", "adultvideo", "adultvideos", 
        "adultweb", "adultxxx", "alt.sex", "altsex", "alt.sex.exhibitionism", "alt.sex.pictures", 
        "altsexst", "alt.sex.stories", "alt.sex.voyeurism", "amateurerotica", "amateurfotos", "amateurhardcore", 
        "amateurindex", "amateurnaked", "amateurnudes", "amateurporn", "amateurpussy", "amateursex", 
        "amateursxxx", "amatuerhardcore", "amatuersex", "ampland", "analaction", "analcum", 
        "analfuck", "analfucking", "analgallery", "analingus", "analpics", "analpicture", 
        "analsex", "analsexpics", "analsexpictures", "analxxx", "animalbeastiality", "animehentai", 
        "animeporno", "animexxx", "asiacarrera", "assfuck", "assfucking", "asshole", 
        "assholes", "asslick", "asspics", "assworship", "autofellatio", "babepix", 
        "badgirls", "bakedchicks", "baldcunt", "baldpussies", "baldpussy", "barecelebs", 
        "barenaked", "barepussy", "beastiality", "beaverboy", "beavershots", "bigballs", 
        "bigblackboobs", "bigblackcocks", "bigblackdicks", "bigblacktits", "bigboob", "bigboobs", 
        "bigbreast", "bigbreastlovers", "bigbreasts", "bigbutt", "bigbutts", "bigclit", 
        "bigclitoris", "bigclits", "bigcock", "bigcocks", "bigcunt", "bigcunts", 
        "bigdick", "bigdicks", "biggestboobs", "biggestdick", "biggesttit", "biggesttits", 
        "bighairyballs", "bighardons", "bighooters", "bignipples", "bigpussies", "bigpussy", 
        "bigtit", "bigtits", "bigtitties", "bigtitts", "bizarresex", "bizarrexxx", 
        "bizzaresex", "blackbondage", "blackboobs", "blackbooty", "blackbutt", "blackcock", 
        "blackcocks", "blackcum", "blackcunt", "blackcunts", "blackdick", "blackdicks", 
        "blackerotica", "blackhardcore", "blacknudes", "blackonblondes", "blackporn", "blackporno", 
        "blackpornography", "blackpussy", "blacksex", "blacksluts", "blacksonblondes", "blacktit", 
        "blacktits", "blacktwat", "blackxxx", "blondepussy", "blondsgay", "bondagefree", 
        "bondagegallery", "bondagelinks", "bondagepics", "bondagepictures", "bondagesex", "bondagestories", 
        "bondagestory", "bukake", "bustybabes", "bustyblondes", "bustyceleb", "butt-fuck", 
        "buttfuck", "buttfucker", "buttfuckers", "buttfucking", "buttholes", "buttman", 
        "buttpics", "buttplug", "buttthumbnails", "cartoonporn", "cartoonsex", "cartoonsxxx", 
        "cartoonxxx", "celebritiesnaked", "celebritiesnude", "celebritiesxxx", "celebritybush", "celebritybutts", 
        "celebritynude", "celebritynudes", "celebrityporn", "celebritypussy", "celebritysex", "celebrityxxx", 
        "celebsxxx", "celebxxx", "centerfolds", "chaseylain", "chatsex", "cheerleadersxxx", 
        "cheerleaderxxx", "chickswithdicks", "christycanyon", "cicciolina", "clitpics", "clitpictures", 
        "closeuppussy", "comixxx", "crotchless", "cruisingforsex", "cumbaths", "cumcoveredcunts", 
        "cumcunt", "cumdrinker", "cumdrinkers", "cumdrinking", "cumdrops", "cumeater", 
        "cumeaters", "cumeating", "cumface", "cumfaces", "cumfacial", "cumfacials", 
        "cumgallery", "cumgargle", "cumguzzlers", "cumincunt", "cumjunkies", "cumlovers", 
        "cummpeg", "cumpic", "cumpics", "cumpicture", "cumpictures", "cumpussy", 
        "cumsluts", "cumsucker", "cumsuckers", "cumsucking", "cumswallow", "cumswallowers", 
        "cumswallowing", "cumtasting", "cumthumbnails", "cunilingus", "cunnilingus", "cuntcum", 
        "cuntfuck", "cuntfucking", "cuntjuice", "cuntlapper", "cuntlick", "cuntlickers", 
        "cuntlicking", "cuntpics", "cuntpictures", "cunts", "cuntstories", "cuntsuckers", 
        "cuntz", "cyberlust", "cybernude", "cyberporn", "cyberpornlinks", "cyberpornsexlinks", 
        "cyberslut", "d’amateur", "danniashe", "dicksex", "dicksuckers", "dicksucking", 
        "digixxx", "directporn", "dirtypictures", "dirtysex", "doggiestyle", "doggystyle", 
        "domatrix", "dominatrixes", "downblouse", "drinkingcum", "drippingcunt", "drippingcunts", 
        "drippingpussy", "easypic.com", "eatcum", "eatingcum", "eatingpussy", "eatpussy", 
        "ebony+ayres", "ebonyporn", "ebonypussy", "ebonysex", "ebonyxxx", "enormoustits", 
        "erosvillage", "eroticanime", "eroticart", "eroticas", "eroticastories", "eroticfiction", 
        "eroticlesbianstories", "eroticmovie", "eroticmovies", "erotico", "eroticos", "eroticpics", 
        "eroticpicture", "eroticpictures", "eroticsites", "eroticsounds", "erotictales", "erotictext", 
        "eroticvideo", "eroticvideos", "eroticwomen", "eroticwriting", "erotikchat", "erotique", 
        "erotismo", "escortservice", "escortservices", "eurosex", "explicitsex", "facecum", 
        "facesit", "facesitters", "fastporn", "fatass", "fatsex", "feetfetish", 
        "feetsex", "felatio", "fellatio", "fellations", "fetishwear", "fettegirls", 
        "fingerbang", "fingerfuck", "flesh4free", "footjobs", "footlicking", "footworship", 
        "fornication", "freeanal", "freeanalsex", "freeass", "freebigboobs", "freebigtit", 
        "freebigtits", "freeblackcunt", "freeblackpussy", "freeblowjob", "freeblowjobs", "freebondage", 
        "freeboobs", "freecum", "freecumshot", "freecumshots", "freecunt", "freecunts", 
        "freedick", "freeerotic", "freeerotica", "freeeroticstories", "freefuck", "freefucking", 
        "freefuckpics", "freegay", "freegaypics", "freehardcore", "freehardcorepics", "freehardcorepictures", 
        "freehardcoreporn", "freehardcoresex", "freehardcoresexpics", "freehentai", "freehooters", "freelargehooters", 
        "freelesbian", "freelesbianporn", "freelesbiansex", "freenakedpic", "freenakedpics", "freenakedpictures", 
        "freenakedwomen", "freenude", "freenudecelebs", "freenudephotos", "freenudepics", "freenudes", 
        "freeporn", "freepornmovies", "freeporno", "freepornography", "freepornopics", "freepornopictures", 
        "freepornos", "freepornpic", "freepornpics", "freepornpictures", "freeporns", "freepornsite", 
        "freepornsites", "freepussy", "freepussypic", "freepussypics", "freepussypictures", "freesex", 
        "freesexchat", "freesexmovies", "freesexnet", "freesexphotos", "freesexpic", "freesexpics", 
        "freesexpicture", "freesexpictures", "freesexsites", "freesexstories", "freesexvideos", "freesexycam", 
        "freeshemale", "freesmut", "freetit", "freetits", "freevoyeur", "freexxx", 
        "freexxxmovie", "freexxxmovies", "freexxxmpeg", "freexxxphotos", "freexxxpic", "freexxxpics", 
        "freexxxpicture", "freexxxpictures", "freexxxstories", "freexxxvideo", "freexxxx", "fuking", 
        "gangbangs", "gratishardcoregalerie", "hardcorecelebs", "hardcorefisting", "hardcorefree", "hardcorefucking", 
        "hardcorehooters", "hardcorejunkie", "hardcorejunky", "hardcoremovie", "hardcoremovies", "hardcorepic", 
        "hardcorepics", "hardcorepictures", "hardcorepix", "hardcoreporn", "hardcoreporno", "hardcorepornography", 
        "hardcorepornos", "hardcorepussy", "hardcoresamples", "hardcoresex", "hardcoresexpictures", "hardcorestories", 
        "hardcorethumbnails", "hardcorevideo", "hardcorevideos", "hardcorexxx", "harddicks", "hardnipples", 
        "hardons", "hardporn", "indiasex", "interacialhardcore", "interacialsex", "interacialxxx", 
        "intercoursepositions", "internetsex", "interracialfucking", "interracialhardcore", "interracialporn", "interracialpornography", 
        "interracialsex", "interracialsexstories", "interracialxxx", "intimatesex", "ittybittytitty", "japaneseporn", 
        "japanesesex", "japansex", "japanxxx", "jennacam.com", "jennajameson", "jennicam", 
        "jerkoff", "jism", "jiz", "jizz", "juicycunts", "juicypussy", 
        "justhardcore", "karasamateurs", "karasxxx", "kascha", "kaylakleevage", "kobetai", 
        "koreasex", "lapdance", "largeclits", "largecunts", "largedicks", "largehooters", 
        "largepussy", "largetit", "largetits", "latinapussy", "latinasex", "latinosex", 
        "latinoxxx", "latinxxx", "legsex", "lesbianerotica", "lesbianhardcore", "lesbianorgies", 
        "lesbianorgy", "lesbianpics", "lesbianpink", "lesbianporn", "lesbian-porno", "lesbianporno", 
        "lesbianpornography", "lesbianpornos", "lesbianpussy", "lesbiansex", "lesbiansexpics", "lesbiansexstories", 
        "lesbianxxx", "lickadick", "lickingpussy", "lindalovelace", "lingeriexxx", "literotica", 
        "littleboobs", "littlepussy", "littletits", "livefucking", "liveporn", "livesex", 
        "livesexcam", "livesexcams", "longdicks", "lovedoll", "lovedolls", "magazinessex", 
        "makinglove", "malaysex", "malenudes", "malesex", "mangaporno", "mangax", 
        "mangaxxx", "manpics", "mansex", "marilynchambers", "massivecocks", "masterbating", 
        "masturbation", "masturbationvideos", "maturefucking", "maturesex", "maturexxx", "megaboobs", 
        "megaporno", "megapussy", "megatits", "mensdicks", "mensex", "m.i.l.f.", 
        "milf", "milfhunterpic", "milfmpegsample", "modelsex", "mondoporn", "monstercocks", 
        "monsterdicks", "motherfucker", "moviepost.com", "mpegsex", "mpegxxx", "muffdiving", 
        "myslutwife", "nacktfotos", "nakedbabes", "nakedblackwomen", "nakedcelebrity", "nakedcelebs", 
        "nakedcheerleader", "nakedchicks", "nakedgirls", "nakedguys", "nakedladies", "nakedlady", 
        "nakedman", "nakedmen", "nakedness", "nakedphotographs", "nakedphotography", "nakedphotos", 
        "nakedpic", "nakedpics", "nakedpicture", "nakedpictures", "nakedpussy", "nakedstars", 
        "nakedwife", "nakedwoman", "nakedwomen", "nastychat", "nastypussy", "nastysex", 
        "nastythumbs", "naturaltits", "naughty.com", "naughtylinks", "naughtylinx", "naughtylynx", 
        "naughtynurses", "netsex", "niceass", "nicetits", "nikkinova", "nikkityler", 
        "nipples", "nookie", "nookies", "nudeactress", "nudeactresses", "nudeamateur", 
        "nudeamateurs", "nudeasianwomen", "nudebabes", "nudebigboobs", "nudeblack", "nudeblackwomen", 
        "nudeblondes", "nudeceleb", "nudeceleberties", "nudecelebraties", "nudecelebrites", "nudecelebrities", 
        "nudecelebrity", "nudecelebs", "nudecollegegirls", "nudefemale", "nudefemales", "nudefree", 
        "nudegay", "nudeimages", "nudeladies", "nudelesbians", "nudemale", "nudemales", 
        "nudeman", "nudemen", "nudepic", "nudepics", "nudepicture", "nudepictures", 
        "nudepornography", "nudepussy", "nuderaider", "nuderedheads", "nudes", "nudesex", 
        "nudestar", "nudestars", "nudevideoconferencing", "nudewoman", "nudewomen", "nudism", 
        "nudist", "nudists", "nudity", "nylonfetish", "nylonsex", "nympho", 
        "nymphos", "olderbabes", "oldersex", "oldersluts", "oldpussy", "oldsex", 
        "oldsluts", "openlegs", "openpussy", "oral4free", "oral-sex", "oralsexpictures", 
        "orgie", "orgies", "orgypics", "orgys", "pantyhosefetish", "pantyhosesex", 
        "peepcam", "persiankitty", "persiankitty.com", "perverted", "picsxxx", "picturesex", 
        "picturesofsex", "picturessex", "pimpserver", "pimpserver.com", "pinkpussy", "pissing", 
        "pixxx", "poontang", "pornagraphy", "porncast", "porncity", "porndirectory", 
        "porne", "pornfree", "pornmovies", "pornno", "pornnude", "porno", 
        "pornoadult", "pornocartoons", "pornochat", "pornodeluxe", "pornoe", "pornofilms", 
        "pornofree", "pornogame", "pornografi", "pornografia", "pornografie", "pornografy", 
        "pornograph", "pornographi", "pornographia", "pornographic", "pornographicpictures", "pornographics", 
        "pornographicvideo", "pornographicvideos", "pornographie", "pornography", "pornographyfree", "pornographyphotos", 
        "pornographypictures", "pornography-sex", "pornographysex", "pornoland", "pornolinks", "pornolynx", 
        "pornomagazines", "pornomovies", "pornompeg", "pornophotos", "pornopic", "pornopics", 
        "pornopicture", "pornopictures", "pornos", "pornosex", "pornosite", "pornosites", 
        "pornostar", "pornostories", "pornovideo", "pornovideos", "pornoxxx", "pornphotos", 
        "pornpics", "pornpictures", "pornpix", "pornpost", "pornqueens", "pornrated", 
        "porns", "pornsex", "pornstar", "pornstories", "porntrack", "pornvideo", 
        "pornvideos", "pornypics", "porstars", "privatesex", "privatex", "privatexx", 
        "privatexxx", "prono", "pronography", "publicnudity", "puffynipples", "purple+passion", 
        "pussyboard", "pussycam", "pussycams", "pussycloseup", "pussycloseups", "pussycum", 
        "pussycunt", "pussyeater", "pussyeaters", "pussyeating", "pussyfuck", "pussyfucking", 
        "pussyhair", "pussyheaven", "pussyjuice", "pussylickers", "pussylicking", "pussylink", 
        "pussylips", "pussyphotos", "pussyporno", "pussys", "pussysex", "pussyshots", 
        "pussythumbnails", "pussytits", "pusy", "racqueldarrian", "rape", "rawlinks", 
        "rawpussy", "rawsex", "realhardcore", "realsex", "redneckporn", "redpussy", 
        "rubberfetish", "russianxxx", "scat", "schiffernude", "seka", "seniorsex", 
        "sex4free", "sex66", "sexacts", "sexadult", "sexaids", "sexamateur", 
        "sexanal", "sexandpictures", "sexaphone", "sexaudio", "sexavi", "sexbondage", 
        "sexboner", "sexbuttfucker", "sexcam", "sexcams", "sexchat", "sexchatrooms", 
        "sexcites", "sexclub", "sexclubs", "sex.com", "sexdating", "sexe", 
        "sexfantasies", "sexfantasy", "sexfilm", "sexgallery", "sexgame", "sexgames", 
        "sexgirl", "sexgirls", "sexgroup", "sexguide", "sexhardcore", "sexhphoto", 
        "sexhungry", "sexhungryjoe", "sexhungryjoes", "sexi", "seximages", "sexis", 
        "sexjapan", "sex.jpg", "sexlinda", "sexlinks", "sexlinx", "sexlive", 
        "sexmagazine", "sexmagazines", "sexmature", "sexmelayu", "sexmodels", "sexmovie", 
        "sexmovies", "sexmpeg", "sexnude", "sexnudity", "sexo", "sexoanal", 
        "sexole", "sexontheinternet", "sexoral", "sexpasswords", "sexphoto", "sexphotos", 
        "sexpic", "sexpicnet", "sexpics", "sexpicture", "sexpictures", "sexpicturesfree", 
        "sexpix", "sexplaza", "sexporn", "sexporno", "sexpositions", "sexpussy", 
        "sexroulette", "sexs", "sexsamples", "sexsearch", "sexsex", "sexsexsex", 
        "sexshare", "sexshops", "sexshow", "sexshows", "sexsite", "sexsites", 
        "sexslave", "sexsound", "sexsounds", "sexsource", "sexspaces", "sexspaces.com", 
        "sexstories", "sexstory", "sexstorys", "sextalk", "sexteen", "sexthumbnails", 
        "sex-toons", "sextoons", "sextour", "sextoy", "sextoys", "sextpus", 
        "sextracker.com", "sextropolis", "sexualbondage", "sexualfantasies", "sexualfantasy", "sexualintercourse", 
        "sexualpictures", "sexualpleasure", "sexualpositions", "sexuncensored", "sexvideo", "sexvision", 
        "sexvote", "sexwomen", "sexworld", "sexx", "sexxx", "sexxxx", 
        "sexxxxx", "sexyamateurs", "sexybabes", "sexyblack", "sexyboobs", "sexybookmark", 
        "sexybookmarka", "sexybookmarks", "sexybutts", "sexycunts", "sexygirl", "sexygirls", 
        "sexyladies", "sexylady", "sexylegs", "sexylingerie", "sexymen", "sexyphotos", 
        "sexypics", "sexypictures", "sexypost", "sexypussies", "sexypussy", "sexysites", 
        "sexystories", "sexywoman", "sexywomen", "shavedcunt", "shavedcunts", "shavedpussies", 
        "shavedpussy", "shavedpussypics", "shavedsluts", "shavedwomen", "shavenpussies", "shavenpussy", 
        "shavepussy", "sheboy", "she-male", "shemale+video", "shemaleyum", "showcam", 
        "showcams", "showercam", "showercams", "slavesex", "smallboobs", "smallbreasts", 
        "smalldicks", "smallpussy", "smalltits", "smut", "smut69", "smutland", 
        "smutserver", "smutshack", "softcore", "softporn", "softpornography", "spankingpage", 
        "spreadpussy", "spycamadult", "stockingsex", "storieserotic", "storiessex", "straightsex", 
        "stretchedcunt", "stripclub", "stripclubs", "stripshow", "striptease", "strokeit", 
        "strokeme", "suckdick", "sucksex", "superchicken", "supersex", "supertits", 
        "swallowcum", "swinger", "swingerclub", "swingers", "swollenclits", "syberporn", 
        "sylviasaint", "teenanal", "teenanalsex", "teenhardcore", "teenie", "teenies", 
        "teennude", "teenpics", "teenporn", "teenporno", "teenpussy", "teensex", 
        "teenslut", "teensluts", "teensuck", "teenxxx", "tgp", "thaipussy", 
        "thaisex", "thehun", "threesomes", "thumblords", "thumbnailssex", "thumbzilla", 
        "tiffanytowers", "tightcunt", "tightpussies", "tightpussy", "tinypussy", "tinytits", 
        "tinytitties", "tisandass", "tit", "titbondage", "titfuck", "titfucking", 
        "tities", "titman", "titsandass", "titsass", "titties", "titts", 
        "titty", "tittyfuck", "tittyfucking", "tittys", "tokyotopless", "tommysbookmark", 
        "toplesswomen", "trannies", "transexual", "transsexuels", "twat", "twats", 
        "twink", "ultradonkey", "ultrahardcore", "uncutcocks", "vaginalintercourse", "vaginapictures", 
        "videoporno", "videosex", "videoxxx", "vintageporn", "virtualsex", "vividtv", 
        "wank", "wankers", "wanking", "wendywhoppers", "wetcunt", "wetcunts", 
        "wetdick", "wetpanties", "wetpussies", "wetpussy", "wetsex", "wetvagina", 
        "whitepussy", "whitesex", "whitetits", "whitexxx", "wifesharing", "wifeswapping", 
        "wildpussy", "wildsex", "womensex", "worldsex", "worldsexguide", "x-rated", 
        "xrated", "x-ratedmovie", "x-ratedmovies", "x-ratedvideo", "x-ratedvideos", "xxx4free", 
        "xxxadult", "xxxadultmovies", "xxxadultvideo", "xxxadultvideos", "xxxbabes", "xxxcam", 
        "xxxcelebrities", "xxxfree", "xxxfreepics", "xxxgalleries", "xxxhardcore", "xxxjapan", 
        "xxxlinks", "xxxmodels", "xxxmovie", "xxxmovies", "xxxmpeg", "xxxpassword", 
        "xxxphoto", "xxxphotos", "xxxpic", "xxx-pics", "xxxpics", "xxxpicture", 
        "xxxpictures", "xxxpicturesfree", "xxxpicx", "xxxpirtures", "xxxporn", "xxxporno", 
        "xxxpussy", "xxx-rated", "xxxrated", "xxxsex", "xxxsites", "xxxsluts", 
        "xxxstories", "xxxteen", "xxxthumbnails", "xxxthumbs", "xxxtoons", "xxxtoys", 
        "xxxvideo", "xxxvideos", "xxxwomen", "xxxx", "xxxxx", "xxxxxx", 
        "filthyfarm", "adultcheck", "erotic", "mistresses", "naughty", 
        "adult", "amateur", "amateurs", "anal", "analau", "poker", 
        "anally", "asian", "swinging", "ass", "orgy", "sexvideos", 
        "babe", "babes", "bare", "glamour", "casino", "bed", 
        "vibrator", "bikini", "bisexual", "blonde", "breasted", "breasts", 
        "busty", "butts", "candy", "caning", "caps", "catholic", 
        "chained", "chested", "chubby", "close-ups", "coupling", 
        "cucumber", "doll", "dolls", "dolly", "dominating", "drinking", 
        "drunk", "fat", "feet", "fingering", "fishnet", "flasher", 
        "footjob", "foreplay", "foreplaying", "girlfriend", "girlfriends", "gymnast", 
        "hairy", "holly", "horse", "housewife", "houswife", "insertion", 
        "insertions", "interracial", "jerka", "juicy", "kissing", "kitty", 
        "lactating", "ladyboy", "lance", "latina", "latins", "leather", 
        "legs", "lesbian", "lesbians", "licking", "lingerie", "lubricants", 
        "mature", "midget", "minor", "mistress", "nude", 
        "older", "olez", "oral", "panties", "pantyhose", "pedro", 
        "peeing", "penetration", "pigtailed", "pleasure", "plump", 
        "plumper", "poser", "posers", "poses", "posing", "prosecuted", 
        "punishment", "reproducing", "sex", "shaved", "shock", "slave", 
        "sleeping", "speculums", "spread", "spreading", "squirting", "stripper", 
        "stripping", "swapping", "thong", "topless", "toying", 
        "trix", "undressing", "uniform", "whipcream", "brazzers", 
        // Russian
        "порно", "порн", "лесб", "гей", "геи", "прон", "секс", "эротика", 
        "ххх", "анал", "минет", "проститутк", "стриптиз", "голая", "голые", 
        "сиськ", "член", "вагин", "оргазм", "мастурбац", "фетиш", "шлюха", 
        "шлюх", "блядь", "бляд", "сперм", "трах", "ебать", "ебля", "хуй", 
        "пизд", "залуп", "хентай", "дрочи", "дроч", "сосать", "сосет",
        "миньет", "куннилингус", "инцест", "групповуха", "свингер", "бдсм",
        // German
        "ficken", "schwanz", "titten", "nackt", "erotik", "fotze", "muschi", 
        "arsch", "wichsen", "blasen", "nutte", "hure", "geil", "bumsen",
        "orgasmus", "analverkehr", "oralverkehr", "masturbieren", "schwul",
        "lesbe", "domina", "sklave", "fesseln", "peitsche",
        // Spanish
        "sexo", "porno", "desnudo", "desnuda", "tetas", "polla", "coño", 
        "culo", "follar", "puta", "prostituta", "orgasmo", "masturbar",
        "corrida", "mamada", "marica", "lesbiana", "anal", "oral",
        "consolador", "vibrador", "lenceria", "erotico", "erotica",
        // French
        "sexe", "porno", "nu", "nue", "bite", "chatte", "cul", "baiser", 
        "putain", "salope", "orgasme", "masturber", "ejaculation", "sodomie",
        "fellation", "lesbienne", "gouine", "partouze", "erotique", "bander",
        // Italian
        "sesso", "porno", "nudo", "nuda", "tette", "cazzo", "fica", "culo", 
        "scopare", "puttana", "troia", "orgasmo", "masturbare", "pompino",
        "lesbica", "erotico", "erotica", "anale", "orale",
        // Portuguese
        "sexo", "porno", "nu", "nua", "peitos", "pau", "buceta", "cu",
        "foder", "puta", "prostituta", "orgasmo", "masturbar", "boquete",
        "lesbica", "erotico", "erotica", "anal", "oral", "gozar",
        // Japanese (romaji)
        "ecchi", "oppai", "hentai", "chikan", "futanari", "yaoi", "yuri",
        "ero", "eroge", "sukebe", "manko", "chinko", "paizuri", "gokkun",
        "nakadashi", "ahegao", "netorare", "ntr", "doujin", "lolige",
        // Chinese (pinyin)
        "seqing", "huangse", "chengrenshipin", "seying", "luoti", "xingjiao",
        "ziweiqi", "koujiao", "gangmen", "nvtong", "nvyou", "semai",
        // Korean (romanized)
        "seonggi", "sekseu", "porno", "nache", "seol", "hwangeum",
        // Polish
        "seks", "porno", "nagi", "naga", "cycki", "kutas", "cipka", "dupa",
        "pierdolic", "kurwa", "dziwka", "orgazm", "masturbacja", "lodzik",
        "lesbijka", "erotyka", "analny", "oralny",
        // Czech
        "sex", "porno", "nahy", "naha", "prsa", "koule", "pica", "prdel",
        "soustat", "kurva", "coura", "orgazmus", "honit", "kourit",
        // Dutch
        "seks", "porno", "naakt", "tieten", "lul", "kut", "kont", "neuken",
        "hoer", "slet", "orgasme", "aftrekken", "pijpen", "lesbisch",
        // Turkish
        "seks", "porno", "ciplak", "meme", "sik", "am", "got", "sikmek",
        "orospu", "orgazm", "mastürbasyon", "lezbiyen", "erotik",
        // Hungarian
        "szex", "porno", "meztelen", "mell", "fasz", "pina", "segg",
        "baszni", "kurva", "ribanc", "orgazmus", "leszbi", "erotikus",
        // Greek (romanized)
        "sex", "porno", "gumnos", "mouni", "pousti", "orgasmos",
        // Arabic (romanized)
        "jins", "seks", "aryan", "zina", "sharmuta", "qahba", "nikah",
        // Hindi (romanized)
        "sex", "chudai", "chut", "lund", "gaand", "randi", "maal",
        // Ukrainian
        "порно", "секс", "еротика", "голий", "гола", "цицьк", "член",
        "пізда", "шльондра", "курва", "трахати", "мінет", "оргазм"
    };
    return words;
}

// Words that mark content as BAD type (blocked entirely)
// These terms are associated with illegal content (CSAM, exploitation)
inline const QSet<QString>& xxxVeryBadWords()
{
    static QSet<QString> words = {
        // Known illegal content markers
        "catgoddess", "gracel", "fatman", "falko", "pthc", "ptsc", "ptsh", 
        "yukikax", "ls-models", "ls-magazine", "ls-land", "ls-island",
        "hussyfan", "lolicon", "shotacon", "toddlercon", "babyshivid",
        "vicky", "valya", "ygwbt", "lsm", "lsmagazine", "childlover",
        "childporn", "childporno", "childmodel", "childmodels",
        "kiddyfuck", "kiddyporn", "kiddysex", "kiddieporn", "kiddypics",
        "pedofilia", "pedophile", "pedophilia", "pedoland", "pedomom",
        "nepi", "preteen", "preteenporn", "preteensex",
        
        // Age markers (illegal context)
        "3yo", "4yo", "5yo", "6yo", "7yo", "8yo", "9yo", 
        "10yo", "11yo", "12yo", "13yo", "14yo", "15yo", "16yo",
        "3y.o", "4y.o", "5y.o", "6y.o", "7y.o", "8y.o", "9y.o",
        "10y.o", "11y.o", "12y.o", "13y.o", "14y.o", "15y.o", "16y.o",
        "3yrs", "4yrs", "5yrs", "6yrs", "7yrs", "8yrs", "9yrs",
        "10yrs", "11yrs", "12yrs", "13yrs", "14yrs", "15yrs",
        
        // Exploitation terms
        "jailbait", "jail-bait", "jbait", "jb-", "jdbait",
        "underage", "under-age", "underaged", "under18",
        "illegal", "illegalcp", "illegalporn",
        
        // Russian illegal terms
        "детское", "детская", "малолетка", "малолетки", "педофил",
        "педо", "цп", "дп", "лоли", "шота",
        
        // German illegal terms
        "kinderporno", "kindersex", "kinderfick", "kinderliebe",
        "minderjährig", "minderjahrig",
        
        // Spanish illegal terms
        "infantil", "menores", "pedofilo", "pedofilia",
        
        // French illegal terms
        "pedophile", "pedopornographie", "mineur", "mineure",
        
        // Other language variants
        "barnporr", "kinderpornografie", "kindermisbruik",
        "dziecko", "dziecięca", "paedophile", "paedo",
        
        // Snuff and extreme illegal content
        "snuff", "snuffx", "snuffporn", "snuffvideo", "realsnuff",
        "necro", "necrophilia", "necrophil",
        
        // Zoophilia (illegal in most jurisdictions)
        "zoophilia", "zoophil", "zooporn", "zoosex", "zoofilia",
        "animalsex", "animalporn", "beastporn", "beastsex",
        "k9sex", "dogsex", "horsesex", "zoofile"
    };
    return words;
}

} // namespace BadWords

#endif // BADWORDS_H
